name: validation
on:
  pull_request:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate catalog
        uses: joelanford/opm-validate@main
        with:
          catalog: ./catalog
